# Generated by Django 3.1 on 2020-08-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
